name: Testy Jednostkowe Qt

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz kod
        uses: actions/checkout@v4

      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalacja zaleznosci systemowych
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-cursor0 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libxcb-shape0 libxcb-xfixes0 libxcb-randr0

      - name: Instalacja Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          arch: 'gcc_64'
          modules: 'qtcharts' 
          cache: true 

      - name: Konfiguracja i Budowanie
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Uruchomienie testów
        env:
          QT_QPA_PLATFORM: offscreen
        run: |
          cd build
          ctest --output-on-failure
